/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Thu Nov 13 17:18:40 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <string.h>
#include <stdio.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1500
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void GeneralLopes_ParseString_Outputs_wrapper(const uint8_T *s,
                          const real_T *s_len,
                          real_T *isParseException,
                          real_T *llcState,
                          real_T *blueCabinetButtonPressed,
                          real_T *isInitOk,
                          real_T *isMotorsOk,
                          real_T *isTreadmillEmpty,
                          real_T *isPatientDefined)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This function parses the output of the first communication
 channel, which holds some always-needed data.
 It also contains the response to a "set state xxx" request (either
 something like "state set to init" or "--- ERROR: ...."). If that is the case,
 then there are also extra responses to "set springspring enable" and "set
 biasforcespring enable". We just ignore these respones and hope that the
 operator is smart enough to notice that the state change did or did not happen.

 The send string looks something like: 
 'set msgID 1;get state;get iscabinetbluebuttonpressed;get isinitok;get isMotorsOk;get isTreadmillEmpty;get isPatientDefined'
 or 
 'set msgID 1;get state;get iscabinetbluebuttonpressed;get isinitok;get isMotorsOk;get isTreadmillEmpty;get isPatientDefined;set state init;set springspring enable;set biasforcespring enable'
 
 The output will look something like (including the quotes):
 msgID=1;"stop";"true";"false";...;"state set to init";"Effect enabled";"Effect enabled"
*/
char *stateStr;
char *emButtonStr;
char *isInitOkStr;
char *isMotorsOkStr;
char *isTreadmillEmptyStr;
char *patientDefinedStr;
char *msgIdStr;
int msgId_int;
int len_int;
char str_copy[1500];

isParseException[0] = 0;

if (s_len[0]==0) 
{
    isParseException[0] = -1;
    return; // then we had no new string to parse
}

// First, break up the string in separate parts. If this 'fails' (i.e.,
// we don't have the data we expected), empty strings will be returned.
len_int = (int)(s_len[0]);
strncpy(str_copy,s,len_int);
str_copy[len_int]=0;
msgIdStr = strtok(str_copy,";"); // note: including "msgID="
stateStr = strtok(NULL,";");
emButtonStr = strtok(NULL,";");
isInitOkStr = strtok(NULL,";");
isMotorsOkStr = strtok(NULL,";");
isTreadmillEmptyStr = strtok(NULL,";");
patientDefinedStr = strtok(NULL,";");

// Now parse them:

// msgID
if (msgIdStr != NULL && strncmp(msgIdStr,"\"msgID=",7)==0) /* We omit checking the number; that will be fine too if the rest is fine */
{ /* Do nothing; it's just an identifier that we got the right packet */ }
else { isParseException[0] = 1; return; }

// State.
// I compare them in a strange order such that the most used are checked first (=faster)
if (stateStr==NULL) { isParseException[0]=1; return; }
else if (strcmp(stateStr,"\"force\"")==0)    llcState[0] = 5;
else if (strcmp(stateStr,"\"off\"")==0)      llcState[0] = 0;
else if (strcmp(stateStr,"\"init\"")==0)     llcState[0] = 1;
else if (strcmp(stateStr,"\"home\"")==0)     llcState[0] = 2;
else if (strcmp(stateStr,"\"stop\"")==0)     llcState[0] = 3;
else if (strcmp(stateStr,"\"position\"")==0) llcState[0] = 4;
else { isParseException[0] = 1; return; }

// emButton
if (emButtonStr==NULL) { isParseException[0]=1; return; }
else if (strcmp(emButtonStr, "\"false\"") == 0) blueCabinetButtonPressed[0] = 0;
else if (strcmp(emButtonStr, "\"true\"") == 0)  blueCabinetButtonPressed[0] = 1;
else { isParseException[0] = 1; return; }

// isInitOK
if (isInitOkStr==NULL) { isParseException[0]=1; return; }
else if (strcmp(isInitOkStr, "\"false\"") == 0) isInitOk[0] = 0;
else if (strcmp(isInitOkStr, "\"true\"") == 0)  isInitOk[0] = 1;
else { isParseException[0] = 1; return; }

// isMotorsOkStr
if (isMotorsOkStr==NULL) { isParseException[0]=1; return; }
else if (strcmp(isMotorsOkStr, "\"false\"") == 0) isMotorsOk[0] = 0;
else if (strcmp(isMotorsOkStr, "\"true\"") == 0)  isMotorsOk[0] = 1;
else { isParseException[0] = 1; return; }

// isInitOK
if (isTreadmillEmptyStr==NULL) { isParseException[0]=1; return; }
else if (strcmp(isTreadmillEmptyStr, "\"false\"") == 0) isTreadmillEmpty[0] = 0;
else if (strcmp(isTreadmillEmptyStr, "\"true\"") == 0)  isTreadmillEmpty[0] = 1;
else { isParseException[0] = 1; return; }

// isPatientDefined
if (patientDefinedStr==NULL) { isParseException[0]=1; return; }
else if (strcmp(patientDefinedStr, "\"false\"") == 0) isPatientDefined[0] = 0;
else if (strcmp(patientDefinedStr, "\"true\"") == 0)  isPatientDefined[0] = 1;
else { isParseException[0] = 1; return; }

// Ignore any extra responses.
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
